name: CI with Env and Secret

on:
  push:
    branches:
      - main

jobs:
  demo-env:
    runs-on: ubuntu-latest

    env:
      APP_NAME: DevOpsApp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print env variable
        run: echo "App name is $APP_NAME"

      - name: Use secret
        run: echo "Secret is ${{ secrets.DEMO_SECRET }}"
