name: CI with Env

on:
  push:
    branches:
      - main

jobs:
  demo-env:
    runs-on: ubuntu-latest
env:
APP_NAME: DevopsApp

    steps:
      - name: Print env variables
        uses: echo "App name is $APP_NAME"
